version: '3'

services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   mautic:
     depends_on:
       - db
     container_name: ${CONTAINER_MT_NAME}
     image: mautic/mautic
     restart: unless-stopped
     volumes:
       - ${MT_FILES}:/var/www/html
       - ./conf.d/uploadsize.ini:/usr/local/etc/php/conf.d/uploadsize.ini
     environment:
       MAUTIC_DB_HOST: ${CONTAINER_DB_NAME}:3306
       MAUTIC_DB_NAME: ${MYSQL_DATABASE}
       MAUTIC_DB_USER: ${MYSQL_USER}
       MAUTIC_DB_PASSWORD: ${MYSQL_PASSWORD}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
    default:
       external:
         name: ${NETWORK}
